plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'com.hotel'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

javafx {
    version = '21'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'com.hotel.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    // MySQL JDBC Driver
    implementation 'com.mysql:mysql-connector-j:8.3.0'
}
